# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class C2c < Formula
  desc "Wrap OpenClaw plugins as standard CLI tools"
  homepage "https://github.com/YangZhengCQ/Claw2cli"
  version "0.2.2-alpha"
  license "MIT"

  depends_on "node" => :recommended

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YangZhengCQ/Claw2cli/releases/download/v0.2.2-alpha/c2c_darwin_amd64.tar.gz"
      sha256 "20c24e11c2b5f679c753ace5add8fef5291c29350bccfe5c941bfbeb7b9150d1"

      define_method(:install) do
        libexec.install Dir["shim"]
        bin.install "c2c"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YangZhengCQ/Claw2cli/releases/download/v0.2.2-alpha/c2c_darwin_arm64.tar.gz"
      sha256 "3efeca54e5444ce729b19448115719a0c5ea89bc50b2a1c46562ab17016ba40e"

      define_method(:install) do
        libexec.install Dir["shim"]
        bin.install "c2c"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/YangZhengCQ/Claw2cli/releases/download/v0.2.2-alpha/c2c_linux_amd64.tar.gz"
      sha256 "a798475badaf17f7fdd120b7cffbc7c282ffec9e87fedfc023f90c6e79c49558"
      define_method(:install) do
        libexec.install Dir["shim"]
        bin.install "c2c"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/YangZhengCQ/Claw2cli/releases/download/v0.2.2-alpha/c2c_linux_arm64.tar.gz"
      sha256 "a99561357597d2587a911fee4a19511bd8677f414030a4449c66b3770c292997"
      define_method(:install) do
        libexec.install Dir["shim"]
        bin.install "c2c"
      end
    end
  end

  test do
    assert_match "c2c", shell_output("#{bin}/c2c --help")
  end
end
